### PR TITLE
Preperations for Glitched logic options

### PR DESCRIPTION
**Pull request by Kewlan**
Before I do more work on this I want to hear if this looks good.
Things might still be broken, but it builds and can generate the mod.

- Turn the ConfitionFn to a vector where the condition iterates through the easiest difficulty to the current set option.
- Add basic easy glitched logic bools.
- Add a few examples in location_access.cpp.

Some examples:
image
image
image
image

When the Logic setting is set to Glitched Easy or Glitched Hard it first checks if the easier conditions are met, other wise it checks the next difficulty until it reaches the set difficulty option.

With this way, we won't have to repeat a lot of code!

### CODE REVIEW

**Comment by cjohnson57** [comment]
The overall idea for this is good. It's probably a lot better to do it this way than to have separate location access files for glitched logic. And the way conditions are processed seems good. Since for the purposes of ConditionsMet() Vanilla logic is equivalent to none, I think these changes for how conditions are processed don't even need to be updated for that PR.

That being said, is having GlitchedEasy and GlitchedHard the approach we want to take? The currently underway glitch logic rewrite for OoTR is instead trickified- Where base glitched logic would be like what your GlitchedEasy is, and harder glitches are handled the way tricks are. So in your first example, you might have like `(IsAdult && CanHover) || (LogicReallyHardGlitch && CanDoReallyHardGlitch)`. Of course, this approach would be more difficult than your idea for just having Easy and Hard logic, so it's also a question of how much free work the person writing glitched logic wants to do, so although I'll mention this idea ultimately it'll be up to that person (and based on this PR it seems that person is you :p)

**Comment by Kewlan** [comment]
> It's probably a lot better to do it this way than to have separate location access files for glitched logic.

Yes, and for any glitchless checks that always return true we don't need to do anything, as Glitched will first check the Glitchless check.

> That being said, is having GlitchedEasy and GlitchedHard the approach we want to take? The currently underway glitch logic rewrite for OoTR is instead trickified- Where base glitched logic would be like what your GlitchedEasy is, and harder glitches are handled the way tricks are. So in your first example, you might have like `(IsAdult && CanHover) || (LogicReallyHardGlitch && CanDoReallyHardGlitch)`. 

This sounds better. We can have a submenu appear below Glitched when it's selected with the tricks inside.

**Comment by Kewlan** [comment]
Commit updated:
image
image
image

**Comment by Kewlan** [comment]
Update: Glitches can now be set to only use certain difficulties. Some examples would be Beginner plus Intermediate, only Beginner, Intermediate and Advanced. Every glitch can still be disabled.

**Pull request merged**
